const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(__dirname+'/../js/gambar.js','utf8');
function setup(){
 const writes=[];const r={id:'r1',latihan:{jenis:'gambarAyat',gambar:'emoji',soalan:[{no:1,perihal:'Peniaga menimbang buah',jawapan:'Peniaga menimbang buah.'},{no:2,perihal:'Budak membayar wang'}]}};
 const c=vm.createContext({TextEncoder,Image:function(){},S:{rph:[r]},sibuk(){},tetapanAI:()=>({prov:'groq',key:'text-secret'}),$:()=>null,rujuk:()=>({doc:()=>({update:async d=>writes.push(JSON.parse(JSON.stringify(d)))})}),jedaKadar:async()=>{},fetchAi:async()=>({})});
 vm.runInContext(source,c);return {c,r,writes};
}
test('image keys never fall back to another text provider',()=>{const {c}=setup();assert.throws(()=>c.kunciGambar(),/Gemini/);c.tetapanAI=()=>({prov:'gemini',key:'image-key'});assert.equal(c.kunciGambar(),'image-key');});
test('scene prompt includes action and selects photocopy-friendly style',()=>{const {c}=setup();const p=c.promptIlustrasi({perihal:'Peniaga menimbang buah',kataBantu:['menimbang']},'garisan');assert.match(p,/Black ink/);assert.match(p,/Peniaga menimbang buah/);assert.match(p,/No emoji/);assert.throws(()=>c.promptIlustrasi({},'warna'),/tiada/);});
test('only embedded raster images are accepted',()=>{const {c}=setup();assert.equal(c.sumberGambarSah('data:image/jpeg;base64,YWJj'),true);for(const v of ['javascript:alert(1)','https://example.com/image','data:image/svg+xml;base64,YWJj','data:image/png;base64,abc" onerror="x'])assert.equal(c.sumberGambarSah(v),false);});
test('text-only or blocked responses are explicit errors',()=>{const {c}=setup();assert.throws(()=>c.imejDaripadaRespons({candidates:[{content:{parts:[{text:'Sorry'}]}}]}),/tidak memulangkan/);assert.equal(c.imejDaripadaRespons({candidates:[{content:{parts:[{inlineData:{mimeType:'image/png',data:'YWJj'}}]}}]}),'data:image/png;base64,YWJj');});
test('image request uses image model and separate key, never text model',async()=>{const {c}=setup();let request;c.fetchAi=async(u,o)=>{request={u,o};return {candidates:[{content:{parts:[{inlineData:{mimeType:'image/png',data:'YWJj'}}]}}]}};c.kecilkanIlustrasi=async d=>d;await c.janaSatuIlustrasi({perihal:'Pasar pagi'},'warna','secret',40000);assert.match(request.u,/gemini-3.1-flash-image/);assert.equal(request.o.headers['x-goog-api-key'],'secret');assert.ok(!request.o.body.includes('secret'));});
test('partial generation saves each success and retries only missing items',async()=>{const {c,r,writes}=setup();let calls=[];c.janaSatuIlustrasi=async s=>{calls.push(s.no);if(s.no===2)throw new Error('timeout');return 'data:image/jpeg;base64,YWJj'};const originalAnswers=JSON.stringify(r.latihan.soalan.map(s=>s.jawapan));assert.equal(await c.lengkapkanGambarLatihan('r1',r.latihan,'warna','key'),1);assert.equal(writes.length,1);assert.equal(r.latihan.gambar,'kartun');c.janaSatuIlustrasi=async s=>{calls.push(s.no);return 'data:image/jpeg;base64,YWJj'};await c.lengkapkanGambarLatihan('r1',r.latihan,'warna','key');assert.deepEqual(calls,[1,2,2]);assert.equal(writes.length,2);assert.equal(JSON.stringify(r.latihan.soalan.map(s=>s.jawapan)),originalAnswers);});
test('quota failure stops requests without hiding successful saves',async()=>{const {c,r,writes}=setup();let count=0;c.janaSatuIlustrasi=async()=>{if(++count===2)throw new Error('HTTP 429');return 'data:image/jpeg;base64,YWJj'};await assert.rejects(c.lengkapkanGambarLatihan('r1',r.latihan,'warna','key'),/429/);assert.equal(writes.length,1);assert.equal(r.latihan.soalan[0].imej,'data:image/jpeg;base64,YWJj');});
test('document size checked before any paid request',async()=>{const {c,r}=setup();r.extra='x'.repeat(810000);let called=false;c.janaSatuIlustrasi=async()=>{called=true};await assert.rejects(c.lengkapkanGambarLatihan('r1',r.latihan,'warna','key'),/terlalu besar/);assert.equal(called,false);});
test('renderer uses actual image and does not expose answer in image alt',()=>{const {c}=setup();c.esc=v=>String(v??'').replace(/</g,'&lt;');vm.runInContext(fs.readFileSync(__dirname+'/../js/rph.js','utf8'),c);const h=c.htmlGambarAyat({gambar:'kartun',soalan:[{no:1,imej:'data:image/png;base64,YWJj',perihal:'SECRET ANSWER',emoji:'OLD',kataBantu:[]}]},false);assert.match(h,/<img src=/);assert.ok(!h.includes('SECRET ANSWER'));assert.ok(!h.includes('OLD'));});
